name = "TensorTrains"
uuid = "44a9e3dd-26ed-4c57-8915-1f5ca631415f"
authors = ["Mi-Song Dupuy <dupuy@ma.tum.de>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
julia = "1.9.3"
